#!/usr/bin/env bash

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This script is a wrapper creating the same user inside container as the one
# running the docker/build.sh outside the container. It also set the home directory
# for the user inside container to match the same absolute path as the workspace
# outside of container.  Do not run this manually. It does not make sense. It is
# intended to be called by ci_build.sh only.

set -e

COMMAND=("$@")

if ! touch /this_is_writable_file_system; then
  echo "You can't write to your filesystem!"
  echo "If you are in Docker you should check you do not have too many images" \
      "with too many files in them. Docker has some issue with it."
  exit 1
else
  rm /this_is_writable_file_system
fi

getent group "${CI_BUILD_GID}" >/dev/null && CI_BUILD_GROUP=$(getent group "${CI_BUILD_GID}" | cut -d: -f1) || addgroup --gid "${CI_BUILD_GID}" "${CI_BUILD_GROUP}"
getent passwd "${CI_BUILD_UID}" >/dev/null || adduser -G "${CI_BUILD_GROUP}" -u "${CI_BUILD_UID}" \
                                           -D -h "${CI_BUILD_HOME}" "${CI_BUILD_USER}"

# This is a grotesque hack to get PYTEST_ADD_OPTS available to all task scripts.
echo "${CI_BUILD_USER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-nopasswd-sudo

# On Mac, /var/run/docker.sock tends to be owned by root. Fix this in the container.
sudo chown "${CI_BUILD_UID}" /var/run/docker.sock

sudo -u "#${CI_BUILD_UID}" --preserve-env \
PYTHONPATH=${PYTHONPATH} \
CI_IMAGE_NAME=${CI_IMAGE_NAME} \
HOME=${CI_BUILD_HOME} \
"${COMMAND[@]}"
